name: dronalms
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.5.3+2
  google_fonts: 3.0.1
  carousel_slider: 4.1.1
  percent_indicator: 4.2.2
  readmore: 2.1.0
  flutter_toggle_tab: 1.2.0
  circular_countdown_timer: 0.2.1
  intl: 0.17.0
  syncfusion_flutter_calendar: 20.1.61
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

